const express=require('express'),cors=require('cors'),bcrypt=require('bcryptjs'),jwt=require('jsonwebtoken'),Database=require('better-sqlite3'),path=require('path');
const app=express(),db=new Database('tasks.db'),SECRET=process.env.JWT_SECRET||'task-demo-secret';
app.use(cors());app.use(express.json());app.use(express.static(path.join(__dirname,'public')));
db.exec(`CREATE TABLE IF NOT EXISTS users(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT,email TEXT UNIQUE,password TEXT,role TEXT DEFAULT 'user');CREATE TABLE IF NOT EXISTS tasks(id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER,title TEXT,description TEXT,status TEXT DEFAULT 'Pending',priority TEXT DEFAULT 'Medium',due_date TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,updated_at TEXT DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES users(id));`);
function auth(req,res,next){let h=req.headers.authorization||'';if(!h.startsWith('Bearer '))return res.status(401).json({error:'Authentication required'});try{req.user=jwt.verify(h.slice(7),SECRET);next()}catch{return res.status(401).json({error:'Invalid or expired token'})}}
app.post('/api/auth/register',async(req,res)=>{let{name,email,password}=req.body;if(!name||!email||!password)return res.status(400).json({error:'All fields are required'});try{let p=await bcrypt.hash(password,10),x=db.prepare('INSERT INTO users(name,email,password) VALUES(?,?,?)').run(name,email,p);res.status(201).json({message:'Registration successful',userId:x.lastInsertRowid})}catch{res.status(409).json({error:'Email already registered'})}});
app.post('/api/auth/login',async(req,res)=>{let u=db.prepare('SELECT * FROM users WHERE email=?').get(req.body.email);if(!u||!(await bcrypt.compare(req.body.password,u.password)))return res.status(401).json({error:'Invalid email or password'});res.json({token:jwt.sign({id:u.id,name:u.name,role:u.role},SECRET,{expiresIn:'2h'}),user:{id:u.id,name:u.name,email:u.email,role:u.role}})});
app.get('/api/tasks',auth,(req,res)=>res.json(db.prepare('SELECT * FROM tasks WHERE user_id=? ORDER BY id DESC').all(req.user.id)));
app.post('/api/tasks',auth,(req,res)=>{let{title,description='',status='Pending',priority='Medium',due_date=''}=req.body;if(!title)return res.status(400).json({error:'Title is required'});let x=db.prepare('INSERT INTO tasks(user_id,title,description,status,priority,due_date) VALUES(?,?,?,?,?,?)').run(req.user.id,title,description,status,priority,due_date);res.status(201).json(db.prepare('SELECT * FROM tasks WHERE id=?').get(x.lastInsertRowid))});
app.put('/api/tasks/:id',auth,(req,res)=>{let t=db.prepare('SELECT * FROM tasks WHERE id=? AND user_id=?').get(req.params.id,req.user.id);if(!t)return res.status(404).json({error:'Task not found'});let v={...t,...req.body};db.prepare('UPDATE tasks SET title=?,description=?,status=?,priority=?,due_date=?,updated_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=?').run(v.title,v.description,v.status,v.priority,v.due_date,t.id,req.user.id);res.json(db.prepare('SELECT * FROM tasks WHERE id=?').get(t.id))});
app.delete('/api/tasks/:id',auth,(req,res)=>{let x=db.prepare('DELETE FROM tasks WHERE id=? AND user_id=?').run(req.params.id,req.user.id);if(!x.changes)return res.status(404).json({error:'Task not found'});res.json({message:'Task deleted'})});
app.get('*',(q,r)=>r.sendFile(path.join(__dirname,'public','index.html')));app.listen(process.env.PORT||3001,()=>console.log('TaskFlow on port 3001'));
